# Design Team Pod Default Configuration

# API Configuration
api:
  host: "0.0.0.0"
  port: 8080
  workers: 1
  log_level: "info"
  cors_origins: ["*"]
  docs_url: "/docs"
  redoc_url: "/redoc"

# Workspace Configuration
workspace:
  base_dir: "/app/workspace"
  projects_dir: "projects"
  output_dir: "output"
  temp_dir: "temp"
  cache_dir: "cache"
  max_project_size_gb: 5
  cleanup_after_days: 30

# Tools Configuration
tools:
  visual_diff:
    default_metrics: ["ssim", "psnr", "mae"]
    output_format: "json"
    ai_provider: "anthropic"
    accuracy_threshold: 0.9
  
  content_scraper:
    max_depth: 3
    timeout_seconds: 30
    user_agent: "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36"
    download_assets: true
    extract_computed_styles: true
    screenshot_viewports:
      - width: 1920
        height: 1080
        name: "desktop"
      - width: 768
        height: 1024
        name: "tablet"
      - width: 375
        height: 667
        name: "mobile"
  
  ai_analyzer:
    default_provider: "anthropic"
    providers:
      openai:
        model: "gpt-4-vision-preview"
        max_tokens: 1500
        temperature: 0.1
      anthropic:
        model: "claude-3-sonnet-20240229"
        max_tokens: 1500
        temperature: 0.1
      gemini:
        model: "gemini-pro-vision"
        max_tokens: 1500
        temperature: 0.1

# Image Processing
image_processing:
  max_file_size_mb: 50
  supported_formats: ["png", "jpg", "jpeg", "webp"]
  default_quality: 95
  compression:
    enabled: true
    quality: 85
    max_width: 2560
    max_height: 1440

# Security Configuration
security:
  max_upload_size_mb: 100
  allowed_domains: []  # Empty means all domains allowed
  rate_limiting:
    enabled: true
    requests_per_minute: 60
  auth:
    basic_auth_realm: "Design Team Pod"
    session_timeout_hours: 24

# Caching Configuration
cache:
  enabled: true
  ttl_hours: 24
  max_size_gb: 2
  cleanup_interval_hours: 6

# Logging Configuration
logging:
  level: "info"
  format: "json"
  handlers:
    - type: "console"
    - type: "file"
      path: "/app/workspace/logs/design-team.log"
      max_size_mb: 100
      backup_count: 5

# Performance Configuration
performance:
  max_concurrent_tasks: 10
  task_timeout_minutes: 30
  memory_limit_mb: 4096
  cpu_limit_percent: 80

# Feature Flags
features:
  ai_analysis: true
  batch_processing: true
  real_time_updates: true
  advanced_metrics: true
  export_reports: true

# Integration Configuration
integrations:
  github:
    enabled: false
    api_url: "https://api.github.com"
    webhook_secret: ""
  
  slack:
    enabled: false
    webhook_url: ""
    channel: "#design-team"
  
  discord:
    enabled: false
    webhook_url: ""

# Validation Rules
validation:
  accuracy_thresholds:
    pixel_perfect: 0.95
    high_accuracy: 0.85
    good_accuracy: 0.75
    acceptable: 0.65
  
  required_metrics:
    - "ssim"
    - "ai_analysis"
  
  quality_gates:
    block_on_low_accuracy: false
    require_ai_validation: true
    min_tools_required: 2

# Backup Configuration
backup:
  enabled: true
  interval_hours: 24
  retention_days: 30
  backup_location: "/app/workspace/backups"
  compress: true
  include_cache: false

# Monitoring Configuration
monitoring:
  health_check_interval_seconds: 30
  metrics_collection: true
  performance_tracking: true
  error_reporting: true
  
  alerts:
    disk_usage_threshold: 0.85
    memory_usage_threshold: 0.90
    error_rate_threshold: 0.05

# Development Configuration
development:
  debug_mode: false
  hot_reload: false
  profiling: false
  mock_ai_responses: false
  
  test_data:
    sample_images_dir: "/app/workspace/test-data/images"
    sample_urls:
      - "https://example.com"
      - "https://httpbin.org/html"

# Production Overrides
production:
  api:
    log_level: "warning"
    cors_origins: ["https://design.xwander.ai"]
  
  security:
    rate_limiting:
      requests_per_minute: 30
    allowed_domains:
      - "xwander.ai"
      - "xwander.com"
      - "xwanderacademy.com"
  
  performance:
    max_concurrent_tasks: 5
    memory_limit_mb: 2048
  
  monitoring:
    alerts:
      disk_usage_threshold: 0.80
      memory_usage_threshold: 0.85